"""Report renderer: converts markdown sections to HTML and PDF."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any


def render_html(sections: list[dict[str, str]], title: str = "Finclaw Report") -> str:
    """Render report sections to styled HTML.

    Each section is {title: str, content: str} where content is markdown.
    """
    try:
        import markdown
    except ImportError:
        # Fallback: wrap in basic HTML
        body = "\n".join(
            f"<h2>{s['title']}</h2>\n<pre>{s['content']}</pre>" for s in sections
        )
        return _wrap_html(body, title)

    body_parts = []
    for section in sections:
        html_content = markdown.markdown(
            section["content"],
            extensions=["tables", "fenced_code"],
        )
        body_parts.append(f'<section>\n<h2>{section["title"]}</h2>\n{html_content}\n</section>')

    return _wrap_html("\n".join(body_parts), title)


def render_pdf(html: str, output_path: Path) -> Path:
    """Convert HTML to PDF using WeasyPrint. Returns the output path."""
    try:
        from weasyprint import HTML
    except ImportError:
        raise ImportError(
            "weasyprint not installed. Install with: pip install finclaw[reports]"
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    HTML(string=html).write_pdf(str(output_path))
    return output_path


def _wrap_html(body: str, title: str) -> str:
    """Wrap body content in a styled HTML document."""
    date_str = datetime.now().strftime("%B %d, %Y")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    max-width: 900px;
    margin: 0 auto;
    padding: 40px 20px;
    color: #1a1a2e;
    line-height: 1.6;
  }}
  h1 {{ color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 10px; }}
  h2 {{ color: #0f3460; margin-top: 30px; border-bottom: 1px solid #e0e0e0; padding-bottom: 5px; }}
  h3 {{ color: #16213e; }}
  table {{
    border-collapse: collapse;
    width: 100%;
    margin: 15px 0;
    font-size: 0.9em;
  }}
  th, td {{
    border: 1px solid #ddd;
    padding: 8px 12px;
    text-align: left;
  }}
  th {{ background-color: #0f3460; color: white; }}
  tr:nth-child(even) {{ background-color: #f8f9fa; }}
  section {{ margin-bottom: 30px; }}
  .header {{
    text-align: center;
    margin-bottom: 40px;
    padding: 20px;
    background: linear-gradient(135deg, #0f3460, #16213e);
    color: white;
    border-radius: 8px;
  }}
  .header h1 {{ color: white; border: none; margin: 0; }}
  .header p {{ color: #b0c4de; margin: 5px 0 0; }}
  .footer {{
    text-align: center;
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid #e0e0e0;
    color: #666;
    font-size: 0.85em;
  }}
  pre {{ background: #f4f4f4; padding: 12px; border-radius: 4px; overflow-x: auto; }}
  code {{ background: #f4f4f4; padding: 2px 4px; border-radius: 3px; }}
</style>
</head>
<body>
<div class="header">
  <h1>{title}</h1>
  <p>Generated by Finclaw &middot; {date_str}</p>
</div>
{body}
<div class="footer">
  <p>This report was generated automatically by Finclaw. Past performance is not indicative of future results.</p>
</div>
</body>
</html>"""
